apiVersion: v1
kind: Service
metadata:
  name: cookbook-search-service
  namespace: cookbook-search
spec:
  selector:
    app: cookbook-search # have to match dployment.yaml spec:selector:matchLabels:app
  ports:
  - protocol: TCP
    port: 50051 # this service will listen on port 50051
    targetPort: 50051 # this service will internally pings port 50051
  type: ClusterIP